project_name: template-bmad
user_skill_level: intermediate
planning_artifacts: '{project-root}/_bmad-output/project-planning-artifacts'
implementation_artifacts: '{project-root}/_bmad-output/implementation-artifacts'
project_knowledge: '{project-root}/docs'
user_name: Helton
communication_language: Brazilian Portuguese
document_output_language: Brazilian Portuguese
output_folder: '{project-root}/_bmad-output'
