installation:
  version: 6.0.0-alpha.19
  installDate: 2025-12-21T17:18:42.033Z
  lastUpdated: 2025-12-21T17:18:42.033Z
modules:
  - core
  - bmm
ides:
  - claude-code
  - codex
  - cursor
  - github-copilot
  - antigravity
  - opencode
  - windsurf
  - rovo-dev
  - auggie
  - cline
  - crush
  - gemini
  - iflow
  - kilo
  - kiro-cli
  - qwen
  - roo
  - trae
